# Generated by Django 2.1.7 on 2019-04-09 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='isEmployeer',
            new_name='isEmployer',
        ),
    ]
