# Generated by Django 2.1.7 on 2019-04-22 17:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=127)),
                ('city', models.CharField(blank=True, max_length=40)),
                ('street', models.CharField(blank=True, max_length=40)),
                ('house_number', models.CharField(blank=True, max_length=5)),
                ('flat_number', models.CharField(blank=True, max_length=5)),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now)),
                ('decription', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DegreeCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('degree_course', models.ManyToManyField(to='job_offers.DegreeCourse')),
            ],
        ),
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('salary_from', models.FloatField()),
                ('salary_to', models.FloatField()),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now)),
                ('job_info', models.ManyToManyField(to='job_offers.JobInfo')),
            ],
        ),
        migrations.CreateModel(
            name='JobOfferLanguage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='JobOfferSkill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='JobTypeInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageLvl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='OfferDegreeCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('degree_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_offers.DegreeCourse')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=127)),
                ('city', models.CharField(blank=True, max_length=40)),
                ('street', models.CharField(blank=True, max_length=40)),
                ('house_number', models.CharField(blank=True, max_length=5)),
                ('flat_number', models.CharField(blank=True, max_length=5)),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now)),
                ('salary_from', models.FloatField(blank=True)),
                ('salary_to', models.FloatField(blank=True)),
                ('document_url', models.CharField(blank=True, max_length=255)),
                ('interest_text', models.TextField(max_length=500)),
                ('decription', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDegreeCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('degree_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_offers.DegreeCourse')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StudentLanguage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_offers.Language')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSkill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_offers.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTypeInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='student_type_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_offers.StudentTypeInfo'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_degree_course',
            field=models.ManyToManyField(to='job_offers.StudentDegreeCourse'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_info',
            field=models.ManyToManyField(to='job_offers.StudentInfo'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_language',
            field=models.ManyToManyField(to='job_offers.StudentLanguage'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_skill',
            field=models.ManyToManyField(to='job_offers.StudentSkill'),
        ),
        migrations.AddField(
            model_name='language',
            name='language_lvl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_offers.LanguageLvl'),
        ),
        migrations.AddField(
            model_name='jobofferskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_offers.Skill'),
        ),
        migrations.AddField(
            model_name='jobofferlanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_offers.Language'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='job_offer_language',
            field=models.ManyToManyField(to='job_offers.JobOfferLanguage'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='job_offer_skill',
            field=models.ManyToManyField(to='job_offers.JobOfferSkill'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='offer_degree_course',
            field=models.ManyToManyField(to='job_offers.OfferDegreeCourse'),
        ),
        migrations.AddField(
            model_name='jobinfo',
            name='job_type_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_offers.JobTypeInfo'),
        ),
        migrations.AddField(
            model_name='company',
            name='job_offers',
            field=models.ManyToManyField(to='job_offers.JobOffer'),
        ),
    ]
