# Generated by Django 2.1.7 on 2019-04-24 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
        ('job_offers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='job_offers',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_degree_course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_info',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_language',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_skill',
        ),
        migrations.RemoveField(
            model_name='studentdegreecourse',
            name='degree_course',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='student_type_info',
        ),
        migrations.RemoveField(
            model_name='studentlanguage',
            name='language',
        ),
        migrations.RemoveField(
            model_name='studentskill',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='department',
            name='degree_course',
        ),
        migrations.RemoveField(
            model_name='jobinfo',
            name='job_type_info',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='job_info',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='job_offer_language',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='job_offer_skill',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='offer_degree_course',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='salary_from',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='salary_to',
        ),
        migrations.RemoveField(
            model_name='language',
            name='language_lvl',
        ),
        migrations.AddField(
            model_name='degreecourse',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='job_offers.Department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobinfo',
            name='job_offer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='job_offers.JobOffer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joboffer',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='employer.Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joboffer',
            name='description',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joboffer',
            name='sallary_from',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joboffer',
            name='sallary_to',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joboffer',
            name='title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobofferlanguage',
            name='job_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='job_offers.JobOffer'),
        ),
        migrations.AddField(
            model_name='jobofferskill',
            name='job_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='job_offers.JobInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='languagelvl',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='job_offers.Language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerdegreecourse',
            name='job_offer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='job_offers.JobOffer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='degreecourse',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobofferlanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='job_offers.Language'),
        ),
        migrations.AlterField(
            model_name='jobofferskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='job_offers.Skill'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='languagelvl',
            name='level',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='offerdegreecourse',
            name='degree_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='job_offers.DegreeCourse'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='JobTypeInfo',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentDegreeCourse',
        ),
        migrations.DeleteModel(
            name='StudentInfo',
        ),
        migrations.DeleteModel(
            name='StudentLanguage',
        ),
        migrations.DeleteModel(
            name='StudentSkill',
        ),
        migrations.DeleteModel(
            name='StudentTypeInfo',
        ),
    ]
