# Generated by Django 2.1.7 on 2019-04-24 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_offers', '0003_auto_20190424_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='language_lvl',
        ),
        migrations.AddField(
            model_name='jobofferlanguage',
            name='language_lvl',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='job_offers.LanguageLvl'),
            preserve_default=False,
        ),
    ]
