# Generated by Django 2.1.7 on 2019-05-24 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_offers', '0006_offermatchstudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offermatchstudent',
            name='student',
        ),
        migrations.AddField(
            model_name='offermatchstudent',
            name='offer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='job_offers.JobOffer'),
            preserve_default=False,
        ),
    ]
