# Generated by Django 2.1.7 on 2019-04-24 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=127)),
                ('street', models.CharField(blank=True, max_length=127, null=True)),
                ('house_number', models.CharField(max_length=20)),
                ('flat_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(max_length=127)),
                ('phone', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
