# Generated by Django 2.1.7 on 2019-05-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_company_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(default='', max_length=127),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.CharField(default='', max_length=127),
        ),
        migrations.AlterField(
            model_name='company',
            name='flat_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='house_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to='gallery_pics/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='street',
            field=models.CharField(blank=True, default='', max_length=127, null=True),
        ),
    ]
