# Generated by Django 2.1.7 on 2019-04-24 11:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_offers', '0002_auto_20190424_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=127)),
                ('city', models.CharField(blank=True, max_length=127, null=True)),
                ('street', models.CharField(blank=True, max_length=127, null=True)),
                ('house_number', models.CharField(blank=True, max_length=20, null=True)),
                ('flat_number', models.CharField(blank=True, max_length=20, null=True)),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now)),
                ('sallary_from', models.IntegerField(blank=True, null=True)),
                ('sallary_to', models.IntegerField(blank=True, null=True)),
                ('document_url', models.CharField(blank=True, max_length=255, null=True)),
                ('interest_text', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDegreeCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('degree_course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='job_offers.DegreeCourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('present', models.FloatField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentLanguage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='job_offers.Language')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSkill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='job_offers.Skill')),
                ('student_info', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.StudentInfo')),
            ],
        ),
    ]
