# Generated by Django 2.1.7 on 2019-04-26 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_studentlanguage_language_lvl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sallary_from',
            new_name='salary_from',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='sallary_to',
            new_name='salary_to',
        ),
    ]
