# Generated by Django 2.1.7 on 2019-04-26 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20190426_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentskill',
            name='student_info',
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='skill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='student.StudentSkill'),
            preserve_default=False,
        ),
    ]
