# Generated by Django 2.1.7 on 2019-05-05 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_offers', '0006_offermatchstudent'),
        ('student', '0008_auto_20190426_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMatchOffer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('percentage', models.FloatField()),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='job_offers.JobOffer')),
            ],
        ),
    ]
