# Generated by Django 2.1.7 on 2019-05-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_studentmatchoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.CharField(blank=True, max_length=511),
        ),
    ]
