# Generated by Django 2.1.7 on 2019-05-23 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='salary_from',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='salary_to',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
