# Generated by Django 2.1.7 on 2019-05-24 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20190523_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmatchoffer',
            name='offer',
        ),
        migrations.AddField(
            model_name='studentmatchoffer',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='student.Student'),
            preserve_default=False,
        ),
    ]
