# Generated by Django 2.1.7 on 2019-05-25 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20190524_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='default.png', upload_to='gallery_pics/%Y/%m/%d/'),
        ),
    ]
